# swagger.yml

openapi: "3.0.0"
info:
  title: "Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"
servers:
  - url: "/api/" # base url http://localhost:5000/api
paths:
  /people: #relative url
    get:
      operationId: "people.read_all" #python function that'll respond to request
      tags: #group operations in UI
        - "People"
      summary: "Read the list of people"
      responses:
        "200": 
          description: "Successfully read people list"
